version: "3.9"
services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${DB_PORT}:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: America/Sao_Paulo
  redis_db:
    image: redis:6.2-alpine
    container_name: redis_db
    ports:
      - "6379:6379"
